name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.LOCAL_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.VPS_SSH_PORT }} -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: ssh -p ${{ secrets.VPS_SSH_PORT }} -v -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} 'echo "SSH connection successful"'

    - name: Deploy to VPS
      run: |
        ssh -p ${{ secrets.VPS_SSH_PORT }} -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} 'cd ${{ secrets.VPS_PROJECT_PATH }} && git pull origin main && npm install && pm2 delete portfolio || : && npm run build-and-serve'
